// Package session provides an in-memory session store.
//
// Security model
// ─────────────
// Sessions are keyed by a random UUID generated by the frontend and sent on
// every request as the  X-Session-ID  header.  The UUID is stored in the
// browser's sessionStorage (cleared when the tab is closed).
//
// API tokens are stored ONLY in this in-memory store – never written to disk,
// never logged, never sent back to the browser.  If the server restarts the
// user must re-authenticate, which is the desired security behaviour.
//
// Concurrent access is safe; each Session value is protected by its own mutex.
package session

import (
	"sync"
	"time"

	"github.com/aiqueneldar/time-sync/backend/internal/models"
)

const defaultTTL = 24 * time.Hour

// Session holds all state for one user session.
type Session struct {
	Mu sync.RWMutex

	ID        string
	CreatedAt time.Time
	LastSeen  time.Time

	// SelectedSystems is the set of system IDs the user has opted into.
	SelectedSystems []string

	// Auth holds the live authentication state for each selected system.
	// Keys are system IDs.  Values are NEVER sent to the browser.
	Auth map[string]*models.AuthResult

	// OIDCPending holds the in-flight OIDC state for each system while the
	// user is completing the identity-provider login in a popup window.
	// Entries are cleared as soon as the code exchange succeeds or the session
	// expires.  Never serialised or sent to the browser.
	OIDCPending map[string]*models.OIDCPendingState

	// Timesheet is the latest time-entry data submitted by the user.
	Timesheet *models.TimesheetInput

	// SyncStatuses tracks the current sync state for each system.
	SyncStatuses map[string]*models.SyncStatus

	// statusCh is a fan-out channel: the sync engine writes status updates here;
	// the SSE handler reads them and streams them to the browser.
	statusCh chan models.SyncStatus
}

// newSession creates an initialised session with the given ID.
func newSession(id string) *Session {
	now := time.Now()
	return &Session{
		ID:           id,
		CreatedAt:    now,
		LastSeen:     now,
		Auth:         make(map[string]*models.AuthResult),
		OIDCPending:  make(map[string]*models.OIDCPendingState),
		SyncStatuses: make(map[string]*models.SyncStatus),
		statusCh:     make(chan models.SyncStatus, 32),
	}
}

// SetAuth stores an AuthResult under the given system ID.
func (s *Session) SetAuth(systemID string, auth *models.AuthResult) {
	s.Mu.Lock()
	defer s.Mu.Unlock()
	s.Auth[systemID] = auth
}

// GetAuth returns the AuthResult for a system, or nil if not authenticated.
func (s *Session) GetAuth(systemID string) *models.AuthResult {
	s.Mu.RLock()
	defer s.Mu.RUnlock()
	return s.Auth[systemID]
}

// SetOIDCPending stores the in-flight OIDC state for a system.
// Called by the auth handler after receiving OIDCRequiredError from an adapter.
func (s *Session) SetOIDCPending(systemID string, state *models.OIDCPendingState) {
	s.Mu.Lock()
	defer s.Mu.Unlock()
	s.OIDCPending[systemID] = state
}

// GetOIDCPending retrieves the in-flight OIDC state for a system, or nil if
// no OIDC flow is in progress for that system.
func (s *Session) GetOIDCPending(systemID string) *models.OIDCPendingState {
	s.Mu.RLock()
	defer s.Mu.RUnlock()
	return s.OIDCPending[systemID]
}

// ClearOIDCPending removes the in-flight OIDC state after a successful (or
// abandoned) code exchange.
func (s *Session) ClearOIDCPending(systemID string) {
	s.Mu.Lock()
	defer s.Mu.Unlock()
	delete(s.OIDCPending, systemID)
}

// SetSyncStatus updates the sync status for a system and broadcasts it to
// any listening SSE handlers.
func (s *Session) SetSyncStatus(status models.SyncStatus) {
	s.Mu.Lock()
	s.SyncStatuses[status.SystemID] = &status
	s.Mu.Unlock()

	// Non-blocking send: if the channel buffer is full, the oldest update is
	// effectively superseded by the next one anyway.
	select {
	case s.statusCh <- status:
	default:
	}
}

// GetAllSyncStatuses returns a snapshot of all sync statuses.
func (s *Session) GetAllSyncStatuses() []models.SyncStatus {
	s.Mu.RLock()
	defer s.Mu.RUnlock()

	out := make([]models.SyncStatus, 0, len(s.SyncStatuses))
	for _, v := range s.SyncStatuses {
		out = append(out, *v)
	}
	return out
}

// StatusCh returns the channel that receives sync-status updates.
// The channel is owned by the session; callers must not close it.
func (s *Session) StatusCh() <-chan models.SyncStatus {
	return s.statusCh
}

// touch updates LastSeen to prevent eviction.
func (s *Session) touch() {
	s.Mu.Lock()
	s.LastSeen = time.Now()
	s.Mu.Unlock()
}

// ─── Store ─────────────────────────────────────────────────────────────────

// Store is the thread-safe registry of all live sessions.
type Store struct {
	mu       sync.RWMutex
	sessions map[string]*Session
	ttl      time.Duration
}

// NewStore creates a Store with the default TTL and starts a background
// eviction goroutine that runs every 10 minutes.
func NewStore() *Store {
	s := &Store{
		sessions: make(map[string]*Session),
		ttl:      defaultTTL,
	}
	go s.evictLoop()
	return s
}

// GetOrCreate returns the session with the given ID, creating it if it does
// not exist.  Every call updates the session's LastSeen timestamp.
func (s *Store) GetOrCreate(id string) *Session {
	// Fast path: read lock.
	s.mu.RLock()
	sess, ok := s.sessions[id]
	s.mu.RUnlock()
	if ok {
		sess.touch()
		return sess
	}

	// Slow path: write lock.
	s.mu.Lock()
	defer s.mu.Unlock()

	// Double-check after acquiring write lock.
	if sess, ok = s.sessions[id]; ok {
		sess.touch()
		return sess
	}

	sess = newSession(id)
	s.sessions[id] = sess
	return sess
}

// Get returns the session with the given ID, or nil if not found.
func (s *Store) Get(id string) *Session {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sess, ok := s.sessions[id]
	if !ok {
		return nil
	}
	sess.touch()
	return sess
}

// Delete removes a session immediately (e.g. on explicit logout).
func (s *Store) Delete(id string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.sessions, id)
}

// evictLoop periodically removes sessions that have been idle longer than the TTL.
func (s *Store) evictLoop() {
	ticker := time.NewTicker(10 * time.Minute)
	defer ticker.Stop()

	for range ticker.C {
		s.evict()
	}
}

func (s *Store) evict() {
	cutoff := time.Now().Add(-s.ttl)

	s.mu.Lock()
	defer s.mu.Unlock()

	for id, sess := range s.sessions {
		sess.Mu.RLock()
		lastSeen := sess.LastSeen
		sess.Mu.RUnlock()

		if lastSeen.Before(cutoff) {
			delete(s.sessions, id)
		}
	}
}
